/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.btv.Admin.Features;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class AllUsers extends javax.swing.JPanel {
    boolean isLocked = false; // temp
    /**
     * Creates new form AllUser
     */
    public AllUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        addUserDialog = new javax.swing.JDialog();
        titleAddDialg = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        addFieldsPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usernameAddLabel = new javax.swing.JLabel();
        usernameAddField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel5 = new javax.swing.JPanel();
        emailAddLabel = new javax.swing.JLabel();
        emailAddField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel6 = new javax.swing.JPanel();
        nameAddLabel = new javax.swing.JLabel();
        nameAddField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        addFieldsPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        addressAddLabel = new javax.swing.JLabel();
        addressAddField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel8 = new javax.swing.JPanel();
        birthAddLabel = new javax.swing.JLabel();
        birthDateChooserAdd = new com.toedter.calendar.JDateChooser();
        javax.swing.Box.Filler filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel9 = new javax.swing.JPanel();
        genderAddLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        maleRadioButtonAdd = new javax.swing.JRadioButton();
        femaleRadioButtonAdd = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        genderAddbuttonGroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        controlSection = new javax.swing.JPanel();
        filterLabel = new javax.swing.JLabel();
        filterOptions = new javax.swing.JComboBox<>();
        filterTextField = new javax.swing.JTextField(16);
        statusOptions = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        addBtn = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        infoSection = new javax.swing.JPanel();
        infoFields = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addressPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        birthPanel = new javax.swing.JPanel();
        birthLabel = new javax.swing.JLabel();
        birthChooser = new com.toedter.calendar.JDateChooser();
        genderPanel = new javax.swing.JPanel();
        genderLabel = new javax.swing.JLabel();
        genderOptionPanel = new javax.swing.JPanel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        emailPanel = new javax.swing.JPanel();
        addressLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        actionPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        lockToggleButton = new javax.swing.JToggleButton();
        loginHistoryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginList = new javax.swing.JList<>();
        friendsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendList = new javax.swing.JList<>();

        addUserDialog.setTitle("Add New User");
        addUserDialog.setMinimumSize(new java.awt.Dimension(860, 295));
        addUserDialog.setModal(true);
        addUserDialog.setResizable(false);
        addUserDialog.setSize(new java.awt.Dimension(900, 320));
        addUserDialog.getContentPane().setLayout(new java.awt.BorderLayout(0, 20));

        titleAddDialg.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleAddDialg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAddDialg.setText("ADD NEW USER");
        titleAddDialg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addUserDialog.getContentPane().add(titleAddDialg, java.awt.BorderLayout.NORTH);

        inputPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        inputPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        addFieldsPanel.setMinimumSize(new java.awt.Dimension(300, 183));
        addFieldsPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        addFieldsPanel.setLayout(new javax.swing.BoxLayout(addFieldsPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel4.setPreferredSize(new java.awt.Dimension(130, 42));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 2));

        usernameAddLabel.setText("Username");
        jPanel4.add(usernameAddLabel, java.awt.BorderLayout.NORTH);

        usernameAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameAddFieldActionPerformed(evt);
            }
        });
        jPanel4.add(usernameAddField, java.awt.BorderLayout.SOUTH);

        addFieldsPanel.add(jPanel4);
        addFieldsPanel.add(filler1);

        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 2));

        emailAddLabel.setText("Email");
        jPanel5.add(emailAddLabel, java.awt.BorderLayout.NORTH);

        emailAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddFieldActionPerformed(evt);
            }
        });
        jPanel5.add(emailAddField, java.awt.BorderLayout.SOUTH);

        addFieldsPanel.add(jPanel5);
        addFieldsPanel.add(filler3);

        jPanel6.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel6.setLayout(new java.awt.BorderLayout(0, 2));

        nameAddLabel.setText("Full name");
        jPanel6.add(nameAddLabel, java.awt.BorderLayout.NORTH);

        nameAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAddFieldActionPerformed(evt);
            }
        });
        jPanel6.add(nameAddField, java.awt.BorderLayout.SOUTH);

        addFieldsPanel.add(jPanel6);
        addFieldsPanel.add(filler4);

        inputPanel.add(addFieldsPanel);

        addFieldsPanel1.setMinimumSize(new java.awt.Dimension(300, 183));
        addFieldsPanel1.setPreferredSize(new java.awt.Dimension(300, 200));
        addFieldsPanel1.setLayout(new javax.swing.BoxLayout(addFieldsPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 2));

        addressAddLabel.setText("Address");
        jPanel7.add(addressAddLabel, java.awt.BorderLayout.PAGE_START);

        addressAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressAddFieldActionPerformed(evt);
            }
        });
        jPanel7.add(addressAddField, java.awt.BorderLayout.SOUTH);

        addFieldsPanel1.add(jPanel7);
        addFieldsPanel1.add(filler6);

        jPanel8.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 2));

        birthAddLabel.setText("Date of birth");
        jPanel8.add(birthAddLabel, java.awt.BorderLayout.CENTER);

        birthDateChooserAdd.setDateFormatString("dd-MM-yyyy");
        jPanel8.add(birthDateChooserAdd, java.awt.BorderLayout.PAGE_END);

        addFieldsPanel1.add(jPanel8);
        addFieldsPanel1.add(filler5);

        jPanel9.setMaximumSize(new java.awt.Dimension(2147483647, 42));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 2));

        genderAddLabel.setText("Gender");
        jPanel9.add(genderAddLabel, java.awt.BorderLayout.NORTH);

        genderAddbuttonGroup.add(maleRadioButtonAdd);
        maleRadioButtonAdd.setSelected(true);
        maleRadioButtonAdd.setText("Male");
        maleRadioButtonAdd.setPreferredSize(new java.awt.Dimension(48, 22));
        maleRadioButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonAddActionPerformed(evt);
            }
        });

        genderAddbuttonGroup.add(femaleRadioButtonAdd);
        femaleRadioButtonAdd.setText("Female");
        femaleRadioButtonAdd.setPreferredSize(new java.awt.Dimension(98, 22));
        femaleRadioButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(maleRadioButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(femaleRadioButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femaleRadioButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleRadioButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel2, java.awt.BorderLayout.CENTER);

        addFieldsPanel1.add(jPanel9);

        inputPanel.add(addFieldsPanel1);

        addUserDialog.getContentPane().add(inputPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(110, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 50));

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setAlignmentY(0.0F);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.setMargin(new java.awt.Insets(2, 5, 3, 5));
        saveButton.setMaximumSize(new java.awt.Dimension(100, 30));
        saveButton.setMinimumSize(new java.awt.Dimension(100, 30));
        saveButton.setPreferredSize(new java.awt.Dimension(100, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel3.add(saveButton);

        addUserDialog.getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        setPreferredSize(new java.awt.Dimension(1080, 768));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("ALL USERS");
        title.setMinimumSize(new java.awt.Dimension(900, 32));
        title.setPreferredSize(new java.awt.Dimension(1080, 32));

        filterLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        filterLabel.setText("Filter by");

        filterOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Name", "Username", "Status" }));
        filterOptions.setPreferredSize(new java.awt.Dimension(70, 30));
        filterOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterOptionsActionPerformed(evt);
            }
        });

        filterTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        filterTextField.setName(""); // NOI18N
        filterTextField.setPreferredSize(new java.awt.Dimension(64, 30));
        filterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextFieldActionPerformed(evt);
            }
        });

        statusOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lock", "Online", "Offline" }));
        statusOptions.setPreferredSize(new java.awt.Dimension(72, 30));
        statusOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusOptionsActionPerformed(evt);
            }
        });
        statusOptions.setVisible(false);

        addBtn.setBackground(new java.awt.Color(48, 162, 255));
        addBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add User");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addBtn.setPreferredSize(new java.awt.Dimension(84, 30));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(48, 162, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setPreferredSize(new java.awt.Dimension(75, 30));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlSectionLayout = new javax.swing.GroupLayout(controlSection);
        controlSection.setLayout(controlSectionLayout);
        controlSectionLayout.setHorizontalGroup(
            controlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlSectionLayout.createSequentialGroup()
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        controlSectionLayout.setVerticalGroup(
            controlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlSectionLayout.createSequentialGroup()
                .addGroup(controlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(controlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterLabel))
                    .addGroup(controlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterTextField.setVisible(false);
        searchButton.setVisible(false);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { Integer.valueOf(1), "vanvan", "Thanh Vân", "123 Vườn Lài", "26-08-2003", "Female", "van@gmail.com", "19-10-2023", "Offline", "thanhvan123"},
                { Integer.valueOf(2), "haha", "Thanh Hà", "123 Vườn Lài", "26-08-2003", "Female", "ha@mail.com", "17-11-2023", "Lock", "thanhha456"},
                { Integer.valueOf(3), "duck", "Nguyên Đức", "456 Vườn Lài", "26-08-2003", "Male", "duc@mail.com", "18-11-2023", "Online", "duck123"}
            },
            new String [] {
                "ID", "Username", "Name", "Address", "Date of birth", "Gender", "Email", "Time create", "Status", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        //TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(userTable.getModel());
        //userTable.setRowSorter(sorter);
        userTable.setRowSorter(new TableRowSorter<TableModel>(userTable.getModel()));
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        tablePanel.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(0).setPreferredWidth(3);
            userTable.getColumnModel().getColumn(9).setResizable(false);
        }
        userTable.getColumnModel().getColumn(9).setMinWidth(0);
        userTable.getColumnModel().getColumn(9).setMaxWidth(0);
        userTable.getColumnModel().getColumn(9).setWidth(0);

        infoFields.setLayout(new java.awt.GridLayout(8, 1, 0, 10));

        usernamePanel.setLayout(new java.awt.BorderLayout());

        usernameLabel.setText("Username:");
        usernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        usernamePanel.add(usernameLabel, java.awt.BorderLayout.CENTER);

        usernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        usernameField.setPreferredSize(new java.awt.Dimension(200, 20));
        usernamePanel.add(usernameField, java.awt.BorderLayout.EAST);

        infoFields.add(usernamePanel);

        namePanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setText("Name:");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        namePanel.add(nameLabel, java.awt.BorderLayout.CENTER);

        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        nameField.setPreferredSize(new java.awt.Dimension(200, 30));
        namePanel.add(nameField, java.awt.BorderLayout.EAST);

        infoFields.add(namePanel);

        addressPanel.setLayout(new java.awt.BorderLayout());

        addressLabel.setText("Address:");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addressPanel.add(addressLabel, java.awt.BorderLayout.LINE_START);

        addressField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        addressField.setPreferredSize(new java.awt.Dimension(200, 30));
        addressPanel.add(addressField, java.awt.BorderLayout.EAST);

        infoFields.add(addressPanel);

        birthPanel.setLayout(new java.awt.BorderLayout());

        birthLabel.setText("Date of birth:");
        birthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        birthPanel.add(birthLabel, java.awt.BorderLayout.LINE_START);

        birthChooser.setDateFormatString("dd-MM-yyyy");
        birthChooser.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        birthChooser.setPreferredSize(new java.awt.Dimension(200, 30));
        birthPanel.add(birthChooser, java.awt.BorderLayout.EAST);

        infoFields.add(birthPanel);

        genderPanel.setLayout(new java.awt.BorderLayout());

        genderLabel.setText("Gender:");
        genderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        genderLabel.setPreferredSize(new java.awt.Dimension(70, 16));
        genderPanel.add(genderLabel, java.awt.BorderLayout.LINE_START);

        genderOptionPanel.setPreferredSize(new java.awt.Dimension(200, 30));
        genderOptionPanel.setLayout(new java.awt.BorderLayout(10, 0));

        genderBtnGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genderOptionPanel.add(maleRadioButton, java.awt.BorderLayout.LINE_START);

        genderBtnGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        femaleRadioButton.setMaximumSize(new java.awt.Dimension(48, 21));
        femaleRadioButton.setMinimumSize(new java.awt.Dimension(48, 21));
        femaleRadioButton.setPreferredSize(new java.awt.Dimension(48, 21));
        genderOptionPanel.add(femaleRadioButton, java.awt.BorderLayout.CENTER);

        genderPanel.add(genderOptionPanel, java.awt.BorderLayout.EAST);

        infoFields.add(genderPanel);

        emailPanel.setLayout(new java.awt.BorderLayout());

        addressLabel1.setText("Email:");
        addressLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        emailPanel.add(addressLabel1, java.awt.BorderLayout.LINE_START);

        emailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        emailField.setPreferredSize(new java.awt.Dimension(200, 30));
        emailPanel.add(emailField, java.awt.BorderLayout.EAST);

        infoFields.add(emailPanel);

        passwordPanel.setLayout(new java.awt.BorderLayout());

        passwordLabel.setText("Password:");
        passwordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        passwordPanel.add(passwordLabel, java.awt.BorderLayout.LINE_START);

        passwordField.setPreferredSize(new java.awt.Dimension(200, 30));
        passwordPanel.add(passwordField, java.awt.BorderLayout.EAST);

        infoFields.add(passwordPanel);

        actionPanel.setMinimumSize(new java.awt.Dimension(160, 0));

        updateButton.setBackground(new java.awt.Color(48, 162, 255));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setPreferredSize(new java.awt.Dimension(130, 35));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        actionPanel.add(updateButton);

        deleteButton.setBackground(new java.awt.Color(239, 149, 149));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setPreferredSize(new java.awt.Dimension(130, 35));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        actionPanel.add(deleteButton);

        lockToggleButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/main/java/com/btv/resources/images/lock-unlock-fill.png"));
        lockToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockToggleButtontoggleLockUser(evt);
            }
        });
        actionPanel.add(lockToggleButton);

        loginHistoryPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN HISTORY");
        jLabel1.setPreferredSize(new java.awt.Dimension(93, 30));
        loginHistoryPanel.add(jLabel1, java.awt.BorderLayout.NORTH);

        loginList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        loginList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(loginList);

        loginHistoryPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        friendsPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LIST FRIENDS");
        jLabel2.setPreferredSize(new java.awt.Dimension(93, 30));
        friendsPanel.add(jLabel2, java.awt.BorderLayout.NORTH);

        friendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        friendList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(friendList);

        friendsPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout infoSectionLayout = new javax.swing.GroupLayout(infoSection);
        infoSection.setLayout(infoSectionLayout);
        infoSectionLayout.setHorizontalGroup(
            infoSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSectionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(infoFields, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginHistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(friendsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        infoSectionLayout.setVerticalGroup(
            infoSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSectionLayout.createSequentialGroup()
                .addGroup(infoSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(friendsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoFields, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(controlSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(controlSection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterOptionsActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        String optionChosen = (String)cb.getSelectedItem();
        if ("None".equals(optionChosen)) {
            filterTextField.setVisible(false);
            statusOptions.setVisible(false);
            searchButton.setVisible(false);
            // Show all data
        }
        else if ("Status".equals(optionChosen)) {
            filterTextField.setVisible(false);
            statusOptions.setVisible(true);
            searchButton.setVisible(true);
        }
        else {
            filterTextField.setVisible(true);
            statusOptions.setVisible(false);
            searchButton.setVisible(true);
        }
    }//GEN-LAST:event_filterOptionsActionPerformed

    private void filterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTextFieldActionPerformed

    private void statusOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusOptionsActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        addUserDialog.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        int viewRow = userTable.getSelectedRow();
        int row = userTable.convertRowIndexToModel(viewRow);
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();

        usernameField.setText(model.getValueAt(row, 1).toString());
        nameField.setText(model.getValueAt(row, 2).toString());
        addressField.setText(model.getValueAt(row, 3).toString());
        String birthDate = model.getValueAt(row, 4).toString();
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse(birthDate);
            birthChooser.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(AllUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gender = model.getValueAt(row, 5).toString();
        if ("Male".equals(gender)) {
            maleRadioButton.setSelected(true);
        }
        else {
            femaleRadioButton.setSelected(true);
        }
        emailField.setText(model.getValueAt(row, 6).toString());
        String status = model.getValueAt(row, 8).toString();
        if("Lock".equalsIgnoreCase(status)) {
            lockToggleButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/main/java/com/btv/resources/images/lock-fill.png"));
        }
        else {
            lockToggleButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/main/java/com/btv/resources/images/lock-unlock-fill.png"));
        }
        passwordField.setText(model.getValueAt(row, 9).toString());
    }//GEN-LAST:event_userTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this,
            "Sure you want to update this user?", "Update comfirmation", JOptionPane.YES_NO_OPTION);
        if(res == JOptionPane.YES_OPTION) {
            // handle update here
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this,
            "Sure you want to delete this user?", "Delete comfirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(res == JOptionPane.YES_OPTION) {
            // handle update here
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void lockToggleButtontoggleLockUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockToggleButtontoggleLockUser
        // TODO add your handling code here:
        isLocked = !isLocked;
        if(isLocked)
        lockToggleButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/main/java/com/btv/resources/images/lock-fill.png"));
        else
        lockToggleButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/main/java/com/btv/resources/images/lock-unlock-fill.png"));

    }//GEN-LAST:event_lockToggleButtontoggleLockUser

    private void usernameAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameAddFieldActionPerformed

    private void emailAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddFieldActionPerformed

    private void nameAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAddFieldActionPerformed

    private void addressAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressAddFieldActionPerformed

    private void maleRadioButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonAddActionPerformed

    private void femaleRadioButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonAddActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addFieldsPanel;
    private javax.swing.JPanel addFieldsPanel1;
    private javax.swing.JDialog addUserDialog;
    private javax.swing.JTextField addressAddField;
    private javax.swing.JLabel addressAddLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JLabel birthAddLabel;
    private com.toedter.calendar.JDateChooser birthChooser;
    private com.toedter.calendar.JDateChooser birthDateChooserAdd;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JPanel birthPanel;
    private javax.swing.JPanel controlSection;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailAddField;
    private javax.swing.JLabel emailAddLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JRadioButton femaleRadioButtonAdd;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JComboBox<String> filterOptions;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JList<String> friendList;
    private javax.swing.JPanel friendsPanel;
    private javax.swing.JLabel genderAddLabel;
    private javax.swing.ButtonGroup genderAddbuttonGroup;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel genderOptionPanel;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JPanel infoFields;
    private javax.swing.JPanel infoSection;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton lockToggleButton;
    private javax.swing.JPanel loginHistoryPanel;
    private javax.swing.JList<String> loginList;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton maleRadioButtonAdd;
    private javax.swing.JTextField nameAddField;
    private javax.swing.JLabel nameAddLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> statusOptions;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleAddDialg;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameAddField;
    private javax.swing.JLabel usernameAddLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
