/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.btv.Admin;

import javax.swing.JComboBox;

/**
 *
 * @author taing
 */
public class UserFriends extends javax.swing.JFrame {

    /**
     * Creates new form UserFriends
     */
    public UserFriends() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headpage = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        options = new javax.swing.JPanel();
        filter = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        numberOptions = new javax.swing.JComboBox<>();
        filterOptions = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 743));
        setMinimumSize(new java.awt.Dimension(1080, 743));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 768));

        headpage.setMaximumSize(new java.awt.Dimension(121, 32));
        headpage.setMinimumSize(new java.awt.Dimension(121, 32));
        headpage.setPreferredSize(new java.awt.Dimension(121, 32));
        headpage.setLayout(new java.awt.BorderLayout());

        header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("FRIENDS");
        headpage.add(header, java.awt.BorderLayout.CENTER);

        filter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filter.setText("Filter by");

        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        searchButton.setText("Search");

        numberOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equal", "Greater", "Less" }));

        filterOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Name", "Number" }));
        Input.setVisible(false);
        numberOptions.setVisible(false);
        filterOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(filter)
                .addGap(18, 18, 18)
                .addComponent(filterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(optionsLayout.createSequentialGroup()
                        .addComponent(Input)
                        .addGap(1, 1, 1))
                    .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addComponent(numberOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        friendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"text", "text", "text", "text", "text"},
                {"text", "text", "text", "text", "text"},
                {"text", "text", "text", "text", "text"},
                {"text", "text", "text", "text", "text"},
                {"text", "text", "text", "text", "text"}
            },
            new String [] {
                "ID", "Username", "Time create", "Direct friends", "Indirect friends"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(friendTable);
        if (friendTable.getColumnModel().getColumnCount() > 0) {
            friendTable.getColumnModel().getColumn(0).setResizable(false);
            friendTable.getColumnModel().getColumn(0).setPreferredWidth(180);
            friendTable.getColumnModel().getColumn(1).setResizable(false);
            friendTable.getColumnModel().getColumn(1).setPreferredWidth(300);
            friendTable.getColumnModel().getColumn(2).setResizable(false);
            friendTable.getColumnModel().getColumn(2).setPreferredWidth(300);
            friendTable.getColumnModel().getColumn(3).setResizable(false);
            friendTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            friendTable.getColumnModel().getColumn(4).setResizable(false);
            friendTable.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void filterOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterOptionsActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        int selection = cb.getSelectedIndex();
        Input.setVisible(true);
        numberOptions.setVisible(true);
        
        if(selection == 0){
            Input.setVisible(false);
            numberOptions.setVisible(false);
        }
        
        else if (selection == 1){
            Input.setVisible(true);
            numberOptions.setVisible(false);
        }
        
        else{
            Input.setVisible(true);
            numberOptions.setVisible(true);
        }
        options.revalidate();
        options.repaint();
    }//GEN-LAST:event_filterOptionsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input;
    private javax.swing.JLabel filter;
    private javax.swing.JComboBox<String> filterOptions;
    private javax.swing.JTable friendTable;
    private javax.swing.JLabel header;
    private javax.swing.JPanel headpage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> numberOptions;
    private javax.swing.JPanel options;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
