/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.btv.User.gui;

import com.btv.User.gui.components.FoundMessListCellRenderer;
import com.btv.User.gui.components.SearchTableModel;
import com.btv.User.gui.components.TableActionCellEditor;
import com.btv.User.gui.components.TableActionCellRender;
import com.btv.User.gui.interfaces.CustomListener;
import com.btv.User.gui.interfaces.SearchListener;
import com.btv.User.gui.interfaces.SearchUserActionEvent;
import com.btv.User.gui.layouts.Layout;
import com.btv.User.helper.MessageStatus;
import com.btv.User.model.ChatMessage;
import com.btv.User.model.User;
import com.btv.User.service.ChatService;
import com.btv.User.service.UserService;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author tvan
 */
public class Search extends javax.swing.JPanel {
    
    private static Search searchPanelInst = null;
    private Layout mainFrame;

    /**
     * Creates new form Search
     */
    private Search(Layout mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        
        foundMessList.setCellRenderer(new FoundMessListCellRenderer());
        
        DefaultListModel<ChatMessage> listChatModel = new DefaultListModel<>();
        foundMessList.setModel((ListModel)listChatModel);
        
        SearchUserActionEvent event = new SearchUserActionEvent() {
            @Override
            public void onChat(int row) {
                SearchTableModel tableModel = (SearchTableModel)tableUserSearch.getModel();
                User user = tableModel.getUser(row);
                
                if(!user.getUsername().equalsIgnoreCase(Chat.getChatPanelInst(null).getCurrentNameChat())) {
                    // load ui
                    CustomListener.getInstance().getChatListener().loadChatUI(user.getId(), user.getUsername(), false, false);

                    // send request
                    ChatService.getChatUserHistory(user.getId());
                }
                
                // change to chat panel
                CustomListener.getInstance().getMenuListener().showChatPanel();
            }

            @Override
            public void onBlock(int row) {
                SearchTableModel tableModel = (SearchTableModel)tableUserSearch.getModel();
                int userId = tableModel.getUser(row).getId();
                
                UserService.blockUser(userId);
            }

            @Override
            public void onAddFriend(int row) {
                SearchTableModel tableModel = (SearchTableModel)tableUserSearch.getModel();
                int userId = tableModel.getUser(row).getId();
                new UserService().addFriend(userId);
            }
        };
        
        CustomListener.getInstance().addSearchListener(new SearchListener() {
            @Override
            public void showFoundUsers(ArrayList<User> listUser) {
                SearchTableModel tableModel = new SearchTableModel(listUser);
                tableUserSearch.setModel(tableModel);
                tableUserSearch.getColumnModel().getColumn(2).setCellRenderer(new TableActionCellRender());
                tableUserSearch.getColumnModel().getColumn(2).setCellEditor(new TableActionCellEditor(event));
            }

            @Override
            public void addFriend(MessageStatus res) {
                JOptionPane.showMessageDialog(mainFrame, res.getMessage(), "Add friend", JOptionPane.INFORMATION_MESSAGE);
            }

            @Override
            public void showFoundMess(ArrayList<ChatMessage> listMess) {
                DefaultListModel<ChatMessage> listChatModel = new DefaultListModel<>();
                for(ChatMessage chatMessage : listMess) {
                    listChatModel.addElement(chatMessage);
                }
                foundMessList.setModel((ListModel)listChatModel);
            }
        });
    }
    
    public static Search getSearchPanelInst(Layout mainFrame) {
        if(searchPanelInst == null)
            searchPanelInst = new Search(mainFrame);
        return searchPanelInst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tableUserSearch = new com.btv.User.gui.components.TableCustom();
        buttonSearchUser = new javax.swing.JButton();
        textFieldSearchMessage = new javax.swing.JTextField();
        comboboxSearch = new com.btv.User.gui.components.ComboboxCustom();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        textFieldSearchUser = new javax.swing.JTextField();
        buttonSearchMessage = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        foundMessList = new javax.swing.JList<>();
        textFieldChatWith = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 768));

        tableUserSearch.setModel(new SearchTableModel(new ArrayList<User>()));
        jScrollPane1.setViewportView(tableUserSearch);
        if (tableUserSearch.getColumnModel().getColumnCount() > 0) {
            tableUserSearch.getColumnModel().getColumn(0).setResizable(false);
            tableUserSearch.getColumnModel().getColumn(1).setResizable(false);
            tableUserSearch.getColumnModel().getColumn(2).setResizable(false);
        }

        buttonSearchUser.setBackground(new java.awt.Color(48, 162, 255));
        buttonSearchUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearchUser.setText("Search");
        buttonSearchUser.setAutoscrolls(true);
        buttonSearchUser.setPreferredSize(new java.awt.Dimension(89, 32));
        buttonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchUserActionPerformed(evt);
            }
        });

        textFieldSearchMessage.setPreferredSize(new java.awt.Dimension(64, 32));
        textFieldSearchMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchMessageActionPerformed(evt);
            }
        });

        comboboxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Username", "Name" }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Search by");

        textFieldSearchUser.setPreferredSize(new java.awt.Dimension(64, 32));
        textFieldSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSearchUserActionPerformed(evt);
            }
        });

        buttonSearchMessage.setBackground(new java.awt.Color(48, 162, 255));
        buttonSearchMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonSearchMessage.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearchMessage.setText("Search");
        buttonSearchMessage.setBorderPainted(false);
        buttonSearchMessage.setPreferredSize(new java.awt.Dimension(89, 32));
        buttonSearchMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchMessageActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Chat with:");
        jLabel3.setPreferredSize(new java.awt.Dimension(62, 32));

        foundMessList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(foundMessList);

        textFieldChatWith.setPreferredSize(new java.awt.Dimension(115, 32));
        textFieldChatWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldChatWithActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("USER");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("MESSAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldChatWith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(136, 136, 136)))
                        .addGap(873, 873, 873))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textFieldSearchMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearchMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboboxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboboxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSearchMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldChatWith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldSearchMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchMessageActionPerformed
        // TODO add your handling code here:
        handleSearchMess();
    }//GEN-LAST:event_textFieldSearchMessageActionPerformed

    private void textFieldSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSearchUserActionPerformed
        // TODO add your handling code here:
        buttonSearchUserActionPerformed(evt);
    }//GEN-LAST:event_textFieldSearchUserActionPerformed

    private void buttonSearchMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchMessageActionPerformed
        // TODO add your handling code here:
        handleSearchMess();
    }//GEN-LAST:event_buttonSearchMessageActionPerformed

    private void buttonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchUserActionPerformed
        // TODO add your handling code here:
        String optionSearch =  (String)comboboxSearch.getSelectedItem();
        String query = textFieldSearchUser.getText();
        if(query.equalsIgnoreCase("")) {
            SearchTableModel tableModel = (SearchTableModel) tableUserSearch.getModel();
            tableModel.clearData();
        }
        else
            new UserService().searchUsers(optionSearch, query);
    }//GEN-LAST:event_buttonSearchUserActionPerformed

    private void textFieldChatWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldChatWithActionPerformed
        // TODO add your handling code here:
        handleSearchMess();
    }//GEN-LAST:event_textFieldChatWithActionPerformed

    public void handleSearchMess() {
        if(textFieldSearchMessage.getText().equals("")) {
            DefaultListModel<ChatMessage> listChatModel = (DefaultListModel<ChatMessage>)foundMessList.getModel();
            listChatModel.removeAllElements();
            return;
        }
        ChatService.searchMessages(textFieldChatWith.getText(), textFieldSearchMessage.getText());
    }
    
    public void loadPanel() {
        textFieldSearchUser.setText("");
        
        SearchTableModel tableModel = (SearchTableModel) tableUserSearch.getModel();
        tableModel.clearData();
        
        textFieldSearchMessage.setText("");
        textFieldChatWith.setText("");
        DefaultListModel<ChatMessage> listChatModel = (DefaultListModel<ChatMessage>)foundMessList.getModel();
        listChatModel.removeAllElements();
        
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearchMessage;
    private javax.swing.JButton buttonSearchUser;
    private com.btv.User.gui.components.ComboboxCustom comboboxSearch;
    private javax.swing.JList<ChatMessage> foundMessList;
    private com.btv.User.gui.components.TableCustom tableUserSearch;
    private javax.swing.JTextField textFieldChatWith;
    private javax.swing.JTextField textFieldSearchMessage;
    private javax.swing.JTextField textFieldSearchUser;
    // End of variables declaration//GEN-END:variables
}
